### ISSUE TITLE
dumpclass 得到的class文件与javac编译得到的class 文件hash存在差异的原因？

### ISSUE THREAD

**Issue by yaokuku123** [hengyunabc/dumpclass#14]
1.通过javac HelloWorld.java 得到 class 文件 HelloWorld.class，使用md5的方式得到该class文件Hash值为「A」；通过 dumpclass 的方式从进程中恢复的 HelloWorld.class 文件，使用md5的方式得到该文件Hash值为「B」。
现象：A != B ，想咨询这个问题的原因，为何恢复后程序的class文件不同？
2.如果 java 直接运行通过 dumpclass 得到的class文件，会报错 “Expected stackmap frame at this location”，类似于没有通过JVM验证，但是加上参数 -noverify 就又可以正常运行了。这个实验似乎与上面Hash值不同的现象呼应。想咨询这里面存在某种机制么，类似于JVM运行时保护？

**Comment by hengyunabc** [comment]
这个确实有点奇怪，可以下个字节码查看工具，看下哪里不一样的了。 或者自己用 javap 看下具体哪里不一样。

或者试下比较新的jvm。

**Comment by yaokuku123** [comment]
<img width="1160" alt="image" src="https://user-images.githubusercontent.com/34773171/206117380-e8932582-c6cf-4767-8aa0-6d2ae42391a0.png">
上方是得到的class字节码对比图，我之后又直接使用sa-jdi工具dump这个class，结果和dumpclass工具是一致的。均和javac编译得到的class字节码存在差异。

**Comment by yaokuku123** [comment]
<img width="649" alt="image" src="https://user-images.githubusercontent.com/34773171/206345314-2e5fdad1-d75b-42ae-9a03-f3786ec955cf.png">
我使用jdk11的 hsdb dump得到的结果依旧证明了javac和dump得到的class字节码存在差异，与java8得到的结果一致

**Comment by yaokuku123** [comment]
我使用arthas dump测试一下结果，发现arthas没问题，dump得到的class字节码和javac编译得到的class字节码是一致的。nb。。

**Comment by hengyunabc** [comment]
可能就是 jvm 里处理了一下。

arthas用的是 ClassFileTransformer 来 dump的。可能jvm只保证了这里返回的 byte[] 和 getResource 获取的是一样的。

然后 jvm 真正把 byte[] 加载处理之后，可能据实际情况做一些变换，或者把一些无用数据清理掉都是有可能的。 hsdb dump 下来的，是这个阶段真正运行的字节码。

需要进jvm源码里看下。

**Comment by yaokuku123** [comment]
get～，感谢解惑
