### ISSUE TITLE
想请教一下调ClassDump的main方法时为什么要用反射？

### ISSUE THREAD

**Issue by lcy362** [hengyunabc/dumpclass#5]
试了一下改回用sun.jvm.hotspot.tools.jcore.ClassDump.main(new String[] { pid }); 直接执行看起来正常情况下也是正常执行，为什么要改成用反射呢？

**Comment by hengyunabc** [comment]
因为要增加一个 url ，用原来的ClassLoader加载不到的。

你可以正常执行，是因为没有走到需要加载外部的 jar file的那里。

**Comment by lcy362** [comment]
看明白了。不过其实main方法最后的这行代码不用改吧。加载外部jar的时候，是用checkRelaunch方法里边新起的线程跑的ClassDump.main(), 走不到checkRelaunch外边来。
